### ISSUE TITLE
Geometry face user selection

### ISSUE THREAD

**Issue by yvanblanchard** [gkv311/OCCT-samples-webgl.github.io#1]
Hello,

Could you please indicate me how to proceed for sélecting a brep face from solid or surface, then get back the face informations (face index, tesselation triangle facets indices). In ordre to change color , compute Area, for example.

Thank you.

**Comment by gkv311** [comment]
This git repository is just a hosting for live WebGL sample built from source code in OCCT repository.

To which project this question belongs? Maybe you want asking it on OCCT forum?

**Comment by yvanblanchard** [comment]
Hello,
I just want to know if there are specificities for user interactions with occt through javascript, and if yes where I can find sample code ?
Thank you.

**Comment by gkv311** [comment]
This specific WebGL sample has minimal JavaScript bindings, so that the main code in C++. And at C++ level you are free to use any [`AIS`](https://dev.opencascade.org/doc/overview/html/occt_user_guides__visualization.html) interfaces, including activation of local selection modes on `AIS_Shape`.

If you have no C++ experience, you might want to look onto projects like 'opencascade.js' (wrapping entire OCCT into JavaScript) or commercial web-libraries based on OCCT exposing more specific features you need.

**Comment by yvanblanchard** [comment]
Thank you for those informations.
